
# Generated by Django 6.0.3 on 2026-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('employment', models.FloatField()),
                ('unemployment_rate', models.FloatField()),
                ('employment_rate', models.FloatField()),
                ('participation_rate', models.FloatField()),
                ('job_growth_index', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]

# Generated by Django 6.0.3 on 2026-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('employment', models.FloatField()),
                ('unemployment_rate', models.FloatField()),
                ('employment_rate', models.FloatField()),
                ('participation_rate', models.FloatField()),
                ('job_growth_index', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]

