# Generated by Django 6.0.3 on 2026-04-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdata',
            name='job_growth_index',
        ),
        migrations.RemoveField(
            model_name='employmentdata',
            name='stability_score',
        ),
    ]
